// Top 250 US Universities and Colleges
export const UNIVERSITIES = [
  "Massachusetts Institute of Technology",
  "Stanford University",
  "Harvard University",
  "California Institute of Technology",
  "University of Chicago",
  "Princeton University",
  "Yale University",
  "Columbia University",
  "University of Pennsylvania",
  "Duke University",
  "Northwestern University",
  "Johns Hopkins University",
  "Dartmouth College",
  "Brown University",
  "Vanderbilt University",
  "Rice University",
  "Washington University in St. Louis",
  "Cornell University",
  "University of Notre Dame",
  "Georgetown University",
  "University of California, Berkeley",
  "University of California, Los Angeles",
  "University of Michigan",
  "Carnegie Mellon University",
  "Emory University",
  "University of Virginia",
  "University of North Carolina at Chapel Hill",
  "Wake Forest University",
  "Tufts University",
  "University of Southern California",
  "New York University",
  "Boston University",
  "Brandeis University",
  "Tulane University",
  "Lehigh University",
  "Northeastern University",
  "Drexel University",
  "Fordham University",
  "American University",
  "University of Miami",
  "Syracuse University",
  "George Washington University",
  "Santa Clara University",
  "Boston College",
  "Villanova University",
  "Purdue University",
  "University of Wisconsin-Madison",
  "Ohio State University",
  "Pennsylvania State University",
  "University of Illinois Urbana-Champaign",
  "University of Washington",
  "University of Georgia",
  "University of Florida",
  "University of Texas at Austin",
  "Texas A&M University",
  "Michigan State University",
  "Indiana University Bloomington",
  "University of Minnesota",
  "University of Colorado Boulder",
  "University of Arizona",
  "Arizona State University",
  "University of Pittsburgh",
  "University of Maryland",
  "Rutgers University",
  "University of Connecticut",
  "University of Iowa",
  "University of Kansas",
  "University of Missouri",
  "University of Nebraska-Lincoln",
  "University of Oklahoma",
  "University of Oregon",
  "Oregon State University",
  "University of Utah",
  "University of Nevada, Las Vegas",
  "University of Nevada, Reno",
  "University of New Mexico",
  "University of Hawaii at Manoa",
  "University of Alaska Fairbanks",
  "Colorado State University",
  "Utah State University",
  "Montana State University",
  "University of Montana",
  "North Dakota State University",
  "University of North Dakota",
  "South Dakota State University",
  "University of South Dakota",
  "University of Wyoming",
  "Idaho State University",
  "University of Idaho",
  "Washington State University",
  "Boise State University",
  "University of California, San Diego",
  "University of California, Davis",
  "University of California, Santa Barbara",
  "University of California, Irvine",
  "University of California, Santa Cruz",
  "University of California, Riverside",
  "University of California, Merced",
  "San Diego State University",
  "San Jose State University",
  "California State University, Los Angeles",
  "California State University, Long Beach",
  "California State University, Fullerton",
  "California Polytechnic State University",
  "University of San Francisco",
  "Loyola Marymount University",
  "Pepperdine University",
  "Chapman University",
  "University of the Pacific",
  "Gonzaga University",
  "Seattle University",
  "University of Portland",
  "Lewis & Clark College",
  "Reed College",
  "Willamette University",
  "University of Puget Sound",
  "Whitman College",
  "University of Denver",
  "Colorado College",
  "Regis University",
  "University of New Hampshire",
  "University of Vermont",
  "University of Maine",
  "University of Rhode Island",
  "University of Massachusetts Amherst",
  "University of Massachusetts Boston",
  "Worcester Polytechnic Institute",
  "Rensselaer Polytechnic Institute",
  "Rochester Institute of Technology",
  "University of Rochester",
  "Clarkson University",
  "Union College",
  "Skidmore College",
  "Colgate University",
  "Hamilton College",
  "Colby College",
  "Bowdoin College",
  "Bates College",
  "Middlebury College",
  "Williams College",
  "Amherst College",
  "Smith College",
  "Mount Holyoke College",
  "Wellesley College",
  "Barnard College",
  "Vassar College",
  "Trinity College",
  "Wesleyan University",
  "Connecticut College",
  "University of Hartford",
  "Quinnipiac University",
  "Fairfield University",
  "Sacred Heart University",
  "Seton Hall University",
  "Montclair State University",
  "New Jersey Institute of Technology",
  "Stevens Institute of Technology",
  "College of New Jersey",
  "Rowan University",
  "Temple University",
  "LaSalle University",
  "Duquesne University",
  "Carnegie Mellon University",
  "University of Delaware",
  "Towson University",
  "Loyola University Maryland",
  "George Mason University",
  "Virginia Tech",
  "Virginia Commonwealth University",
  "James Madison University",
  "College of William & Mary",
  "University of Richmond",
  "Hampden-Sydney College",
  "Washington and Lee University",
  "Davidson College",
  "Elon University",
  "Appalachian State University",
  "North Carolina State University",
  "Duke University",
  "University of South Carolina",
  "Clemson University",
  "College of Charleston",
  "Furman University",
  "Wofford College",
  "University of Georgia",
  "Georgia Tech",
  "Georgia State University",
  "Morehouse College",
  "Spelman College",
  "Mercer University",
  "University of Alabama",
  "Auburn University",
  "University of Alabama at Birmingham",
  "University of Mississippi",
  "Mississippi State University",
  "Louisiana State University",
  "Tulane University",
  "University of New Orleans",
  "University of Tennessee",
  "Vanderbilt University",
  "Belmont University",
  "Rhodes College",
  "Sewanee: The University of the South",
  "University of Kentucky",
  "University of Louisville",
  "Centre College",
  "Transylvania University",
  "University of Arkansas",
  "Arkansas State University",
  "University of Texas at Dallas",
  "University of Texas at San Antonio",
  "University of Houston",
  "Texas Christian University",
  "Southern Methodist University",
  "Texas Tech University",
  "Baylor University",
  "Trinity University",
  "Rice University",
  "University of North Texas",
  "Oklahoma State University",
  "University of Tulsa",
  "Kansas State University",
  "Wichita State University",
  "Iowa State University",
  "Drake University",
  "Creighton University",
  "University of Nebraska Omaha",
  "Marquette University",
  "University of Wisconsin-Milwaukee",
  "Lawrence University",
  "Beloit College",
  "Carleton College",
  "Macalester College",
  "St. Olaf College",
  "University of St. Thomas",
  "Hamline University",
  "DePaul University",
  "Loyola University Chicago",
  "Illinois Institute of Technology",
  "University of Illinois Chicago",
  "Illinois Wesleyan University",
  "Knox College",
  "Lake Forest College",
  "Denison University",
  "Kenyon College",
  "Oberlin College",
  "Ohio Wesleyan University",
  "Wooster College",
  "Miami University",
  "Xavier University",
  "University of Dayton",
  "Case Western Reserve University",
  "Cleveland State University",
  "Bowling Green State University",
  "Ball State University",
  "Butler University",
  "DePauw University",
  "Earlham College",
  "Wabash College",
  "University of Michigan-Dearborn",
  "Michigan Technological University",
  "Western Michigan University",
  "Grand Valley State University",
  "Hope College",
  "Kalamazoo College",
  "Calvin University",
  "Howard University",
  "Georgetown University",
  "Catholic University of America",
  "Gallaudet University",
  "Florida State University",
  "University of Central Florida",
  "University of South Florida",
  "Florida International University",
  "Florida Atlantic University",
  "Stetson University",
  "Rollins College"
];

export function searchUniversities(query) {
  if (!query || query.length < 2) return [];
  const q = query.toLowerCase();
  return UNIVERSITIES.filter(u => u.toLowerCase().includes(q)).slice(0, 8);
}
